# Generated by Django 5.0.4 on 2024-04-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="media/catalog",
                verbose_name="Изображение (превью)",
            ),
        ),
    ]
