# Generated by Django 4.2.2 on 2024-05-27 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bloging", "0002_blog_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="owner",
        ),
    ]
